algorithm:
  common:
    evaluation:
      large:
        frequency: 20   # after how many small evals there is a large one
        multi_step_evaluations: [ 1, 3 ]
        animation_task_indices: [ 0, 1, 2]   # which tasks to plot.
  lts_gns_prodmp:
    evaluation:
      large:
        num_z_samples_per_animation_task: 3 # how many different animations with different z samples should be computed
  lts_gns:
    evaluation:
      large:
        num_z_samples_per_animation_task: 3 # how many different animations with different z samples should be computed
        training_gmm_indices: [0, 1]  # which gmms to use for the training set

env:
  common:  # common parameters that are used by all environments/tasks
    visualization:
      num_frames: 100  # maximum number of frames to visualize. -1 for "all"
      fps: 5
      matplotlib:
        show_legend: False
        fig_size: 12
        dpi: 100
      plotly:
        button_name: "Yoinks"

  multi_modal_toy_task:
    visualization:
      backend: matplotlib  # either matplotlib or plotly. Some tasks only support one or the other
      limits:
        xlim: [ -1.25, 1.75 ]
        ylim: [ -1.25, 1.75 ]
        zlim: [ -1.25, 1.75 ]

  deformable_plate:
    visualization:
      backend: matplotlib  # either matplotlib or plotly. Some tasks only support one or the other
      limits:
        xlim: [ -1.25, 1.75 ]
        ylim: [ -1.25, 1.75 ]
        zlim: [ -1.25, 1.75 ]
    postprocess:
      batch:
        max_eval_batch_size: 10
    debug:
      max_tasks_per_split: null


  tissue_manipulation:
    visualization:
      backend: plotly  # either matplotlib or plotly. Some tasks only support one or the other
      limits:
        xlim: [ -1.0, 1.0 ]
        ylim: [ -1.0, 1.0 ]
        zlim: [ -1.5, 2.0 ]

  multi_decision_toy_task:
    visualization:
      backend: matplotlib  # either matplotlib or plotly. Some tasks only support one or the other
      limits:
        xlim: [ -1.25, 1.75 ]
        ylim: [ -1.25, 1.75 ]
        zlim: [ -1.25, 1.75 ]

  pybullet_uniform:
    visualization:
      backend: plotly  # either matplotlib or plotly. Some tasks only support one or the other
      limits:
        xlim: [ 0.0, 1.0 ]
        ylim: [ 0.0, 1.0 ]
        zlim: [ 0.0, 1.0 ]
  pybullet_square_cloth:
    visualization:
      backend: plotly  # either matplotlib or plotly. Some tasks only support one or the other
      limits:
        xlim: [ 0.0, 1.0 ]
        ylim: [ 0.0, 1.0 ]
        zlim: [ 0.0, 1.0 ]
