# This is the main config file for default parameters for all hyperparameter and task parameter.
# Every config file should import this. The project will run with these parameters, no matter what.

name: "SLURM"   # MUST BE "SLURM"

# Required
partition: "gpu"
job-name: "lts_gns"    # this will be the experiments name in slurm

# Required - Cluster Specific
num_parallel_jobs: 99
ntasks: 1
cpus-per-task: 2
mem-per-cpu: 15000
time: 1440  # in minutes

sbatch_args: # Dictionary of SBATCH keywords and arguments
  gres: "gpu:1"

slurm_log: "./output/slurmlog" # optional. dir in which slurm output and error logs will be saved.
---
name: debug_mgn_deformable_plate

import_path: ../default.yml
import_exp: DEFAULT

repetitions: 1 # number of times one set of parameters is run
reps_per_job: 1 # number of repetitions in each job. useful for paralellization. defaults to 1.
reps_in_parallel: 1 # number of repetitions in each job that are executed in parallel. defaults to 1.

iterations: 3 # number of iterations of the algorithm, usually about 500 when it starts overfitting

params:
  recording:
    wandb:
      enabled: True  # right now disabled to not spam runs during debugging

  algorithm:
    name: mgn_prodmp  # ms_mgn

    common:
      training:
        batches_per_epoch: 10
      evaluation:
        large:
          recompute_edges: False  # whether to recompute the (mesh-collider) edges for the evaluation or not.
          # if both true and false are in the list, both options are evaluated.
          multi_step_evaluations: [ 1 ]
          animation_task_indices: [ 0, 1, 2, 3, 4, 27, 28, 29 ]   # which tasks to plot.
          initial_eval: True
      simulator:
        gnn:
          latent_dimension: 128
        decoder:
          latent_dimension: 64
        mp_config:
          tau: 1.0
          learn_tau: True
          min_tau: 0.3
          max_tau: 3.0
          mp_type: prodmp
          mp_args:
            dt: 0.02  # 1 / 50
            num_basis: 10
            relative_goal: True
            alpha: 25.0
            alpha_phase: 2.0
            basis_bandwidth_factor: 1.0
            num_basis_outside: 0

  env:
    name: deformable_plate
    deformable_plate:
      preprocess:
        use_canonic_mesh_positions: False
    common:
      statistics:
        use_output_normalizer: True
      preprocess:
        save_load:
          path_to_datasets: /mnt/Data/lts_gns
      training:
        add_training_noise: True
      postprocess:
        input_mesh_noise: 0.01
        batch:
          max_train_batch_size: 50
      debug:
        max_tasks_per_split: null
      batch:
        max_train_batch_size: 32

